services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    container_name: "redis"
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]


  postgres:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "demodb"
    command: ["postgres", "-N", "1000"]
    container_name: "postgres"
